@startuml UserUML1.1

left header
<font color=000 size=16><b>ID:</b> UC_1
<font color=000 size=16><b>Назва:</b> Ідентифікація зареєстрованного користувача  
<font color=000 size=16><b>Учасники:</b> Користувач, Програма
<font color=000 size=16><b>Передумови:</b> Користувач має токен доя ідентифікації
<font color=000 size=16><b>Результат:</b> Отримання доступу до бази даних 
<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Надсилаэ запит на отримання форми ідентифікації
;

|Програма|
: Надсилає форму для ідентифікації
 ;

|Користувач|
: Вводить ім'я користувача, спеціальний токен;


|Програма|
:Перевіряє коректність даних;
note right #ffaaaa
<b> Можливо 
<b> Відправка повідомлення про помилку
end note

:Надає доступ до бази;



|Користувач|
:Отримує доступ;
stop;

@enduml
