@startuml UserUML1.3

left header
<font color=000 size=16><b>ID:</b> UC_1
<font color=000 size=16><b>Назва:</b> Взаємодія користувача з програмою
<font color=000 size=16><b>Учасники:</b> Користувач, Програма
<font color=000 size=16><b>Передумови:</b> Користувач має токен доя ідентифікації та пройшов ідентифікацію
<font color=000 size=16><b>Результат:</b> Внесення змін до бази даних 
<font color=000 size=16><b>Основний сценарій:</b>
end header

|Користувач|
start
: Надсилає запит на зміну бази даних;

|Програма|
: Надсилає форму для зміни бази;

|Користувач|
: Може змінити власні дані;
note left
<b> Можливо
 видалити власний аккаунт
end note

|Користувач|
: Надсилає запит до бази;

|Програма|
:Перевіряє коректність даних;

: Додає зміни до бази;
stop;
@enduml
