@startuml AdminUML
left header
<font color=000 size=16><b>ID:</b> UC_2
<font color=000 size=16><b>Назва:</b> Взаємодія з програмою  адміністратора 
<font color=000 size=16><b>Учасники:</b> Користувач, Програма
<font color=000 size=16><b>Передумови:</b> Адмін бажає здійснити взаємодію з програмою
<font color=000 size=16><b>Результат:</b> Внесення змін у базі
<font color=000 size=16><b>Основний сценарій:</b>
end header 
left to right direction
skinparam BackgroundColor Bisque
skinparam ArrowFontName Colibri
skinparam UsecaseBorderThickness 3
skinparam UsecaseFontSize 15
skinparam PackageFontStyle italic
skinparam packageStyle rectangle
skinparam UsecaseFontName Times New Romanskinparam 
actor Admin
actor Database
rectangle Robin {
  Admin -- (Видалити юзера)
  (Видалити юзера) -- Database
  Admin -- (Видалити базу)
  (Видалити базу) -- Database
  Admin -- (Оновити базу)
  (Оновити базу) -- Database
  usecase UC1 as "<b>Редагувати базу
  --
  Додати інформацію
  Видалити інформацію
  "
  Admin - UC1
  UC1 - Database


}

@enduml