@startuml GuestUML

left header
<font color=000 size=16><b>ID:</b> UC_1
<font color=000 size=16><b>Назва:</b> Взаємодія незареєстрованого  користувача  
<font color=000 size=16><b>Учасники:</b> Користувач, Програма
<font color=000 size=16><b>Передумови:</b> Користувач не має спеціального токену
<font color=000 size=16><b>Результат:</b> Отримання токену для логування 
<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Надсилаэ запит на отримання реєстраційної форми
;

|Програма|
: Надсидає форму для реєстрації
 ;

|Користувач|
: Вводить адресу
електронної пошти, імя'я користувача;
note right #ffaaaa
<b> Можливо
<b> Виникнення помилки у введених даних
end note

: Задає пароль;
note right
<b> Обирає пароль запропонований програмою  
end note

|Програма|
:Створює унікальний токен;

:Відправляє токен на пошту;


|Користувач|
:Отримує токен;
stop;

@enduml
