@startuml GuestUML
left header
<font color=000 size=16><b>ID:</b> UC_1
<font color=000 size=16><b>Назва:</b> Взаємодія з програмою не залогованого користувача
<font color=000 size=16><b>Учасники:</b> Користувач, Програма
<font color=000 size=16><b>Передумови:</b> Користувач не має спеціального токену
<font color=000 size=16><b>Результат:</b> Отримання доступу до програми
<font color=000 size=16><b>Основний сценарій:</b>
end header

left to right direction
skinparam packageStyle rectangle
actor Guest
actor Database
skinparam BackgroundColor Bisque
skinparam ArrowFontName Colibri
skinparam UsecaseBorderThickness 3
skinparam UsecaseFontSize 16
skinparam PackageFontStyle italic
skinparam UsecaseFontName Times New Roman
rectangle Robin {
  Guest --(Відправити запит на реєстрацію)
  Guest --(Відправити запит на логування)
  (Відправити запит на логування) - Database
  (Відправити запит на реєстрацію) ..> (Ввести своє ім'я):include
  (Відправити запит на реєстрацію) ..> (Ввести пошту):include
  (Ввести пошту) -- Database
  (Ввести своє ім'я) -- Database
  (Отримати повідомлення про помилку) ..> (Відправити запит на реєстрацію):extend
  (Отримати повідомлення про помилку) .> (Відправити запит на логування):extend
  (Отримати токен доступу) <. (Відправити запит на логування):include
  (Отримати токен доступу) <.. (Відправити запит на реєстрацію):include
  }
@enduml