@startuml ER-model

skinparam monochrome true
skinparam	shadowing false

title
  <font size=14 color=black>
	<b>Robin ODMS
	ER-модель
end title

entity "<b>Open Data" as Data {
	data_id
	--
	address
	--
	data_type
	data_title
	description
	version
	--
	used_by
	total_rows
	issues
	--
	first_publish
	last_publish
}

entity "<b>User" as User {
	user_id
	--
	status
	name
	display_name
	email
	password
	--
	is_pro
	--
	created_at
	updated_at
}

entity "<b>Owner" as Owner {
	ownership_type
	--
	promoted_by
	promoted_at
}

entity "<b>Service" as Service {
	service_id
	--
	name
	description
	--
	created_at
	updated_at
}

entity "<b>Develop" as Develop {
	developer_type
	--
	promoted_by
	promoted_at
}

Data -- Owner
Data -- Service
Service -- Develop
User -- Owner
User -- Develop

@enduml
