@startuml firsrER
title
  <font size=16 color=black><b>ER-модель
end title


left to right direction
skinparam ClassBackgroundColor Bisque
skinparam ClassFontColor Black
skinparam ClassFontName Times New Roman black
skinparam PackageBackgroundColor #DD6B47
allow_mixing
skinparam ObjectBackgroundColor White
skinparam ArrowColor #EAB327
 
  object Admin
  object User 
  entity Role{
  name: Enum
  }
  entity RequestValidator{ 
  }
  User ..> Role: instance of
  Admin ..> Role: instance of
  Role "0..1"-> RequestValidator
  
  

 package "UserDatabase" <<Database>>{
   entity "RequestHandler" as RH #EAAA4A {

   }
   entity "RequestResponse" as RR #EAAA4A {  
   }
   RequestValidator "0..1"--> RH
   RH "1"--> RR
   RR "1"--> RequestValidator
   
 } 

  package "GeneralDatabase" <<Database>>  {
    entity "RequestHandler"#EAAA4A {
    }
    entity "RequestResponse" #EAAA4A

  }
  RequestValidator "0..1" --> RequestHandler
  RequestHandler "1"--> RequestResponse
  RequestResponse "1"--> RequestValidator

@enduml