@startuml UserUML1.2

left header
<font color=000 size=16><b>ID:</b> UC_1
<font color=000 size=16><b>Назва:</b> Взаємодія користувача з  програмою
<font color=000 size=16><b>Учасники:</b> Користувач, Програма
<font color=000 size=16><b>Передумови:</b> Користувач має права 
адміністратора
<font color=000 size=16><b>Результат:</b> Внесення змін власного профілю 
<font color=000 size=16><b>Основний сценарій:</b>
end header

|Користувач|
start
: Надсилає запит про відображення інформації за бажанням
;

|Програма|
: Надсилає  дані ;
|Користувач|
:Може змінити дані бази користувачів
Видалити базу
Додати нову
;
note left
<b> Можливо
 Змінити алгоритм генерації токену
end note

|Користувач|
: Надсилає запит до бази;

|Програма|
:Перевіряє коректність даних;
note right #ffaaaa
<b> Можливо 
<b> Відправка повідомлення про помилку
end note

: Додає зміни до бази користувачів та усіх структур даних де були внесені зміни;
stop;
@enduml
